### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by frenchfrysays3** [nathancartlidge/powertoys-run-agda#1]
i followed the instructions in the version download, won't appear

**Comment by frenchfrysays3** [comment]
![Uploading Screenshot 2024-07-08 131810.png…]()

**Comment by nathancartlidge** [comment]
hi! that screenshot doesn't seem to have loaded properly for me - can you try reuploading it?

Some basic sanity checks you can try:
- Is the folder you put the plugin into definitely the one used by version of powertoys you are running? (ie: do other plugins work)
- Did you enable the plugin in the powertoys run settings
- Have you tried rebooting?

Also - what version and OS are you using?

**Comment by frenchfrysays3** [comment]
I am using powertoys version 0.83.0 (latest) and Windows 10 22H2 and the build is 19045.4717. I seem to have lost the picture so I can't reupload.
